### ISSUE TITLE
Views display not working

### ISSUE THREAD

**Issue by jromine** [backdrop-contrib/references#1]
The References views display is not showing any values. The preview in the views edit screen is blank as is the display for the field autocomplete results.

**Comment by jromine** [comment]
This commit https://github.com/backdrop-contrib/references/commit/ad4363a9aa7b1eeba35d20f7420da45f5cf0a375 fixes the problem, but it's not clear why or if this is the correct fix.

**Comment by olafgrabienski** [comment]
I can confirm that the commit fixed the issue. The References view display works on a Backdrop 1.6.x site. Should this issue be closed now (although it's not clear why the commit fixed it)?
