### ISSUE TITLE
Reference field cannot be left blank

### ISSUE THREAD

**Issue by herbdool** [backdrop-contrib/references#6]
I need to confirm this on a fresh install but on a site upgraded from Drupal 6 (to Drupal 7 then Backdrop) where node reference module is replaced with references, when I leave the node reference field unassigned I get:

```
EntityStorageException: SQLSTATE[HY000]: General error: 1366 Incorrect integer value: '' for column 'field_example_reference_value' at row 1 in NodeStorageController->save() (line 301 of /path-to-backdrop/core/modules/node/node.entity.inc).
```

**Comment by herbdool** [comment]
I don't get the same error on a fresh Backdrop install so this probably has something to do with the upgrade from Drupal 7 References module.

**Comment by olafgrabienski** [comment]
Just tested with BD 1.6 and the current *References* release: created a node without filling in a node reference in the relevant field. There were no problems.
