### ISSUE TITLE
Security issue DRUPAL-SA-CONTRIB-2017-38

### ISSUE THREAD

**Issue by Al-Rozhkov** [backdrop-contrib/references#7]
https://www.drupal.org/node/2869138

> There is a known security issue with the module that has not been fixed by the maintainer.

I didn't find any details about vulnerability. This module has 120k installs in d7 and one of the most popular modules in Backdrop according to information from https://backdropcms.org/project/usage

**Comment by Al-Rozhkov** [comment]
D7 project was updated and available again.
https://www.drupal.org/project/references

**Comment by klonos** [comment]
Since this was a security release, I've committed the changes made in the d.org module as is. @Al-Rozhkov are you using this module in production? If so, can you please have a quick check and of you think it's OK, lets tag a new release.

**Comment by klonos** [comment]
Pinging @jromine (listed as the current maintainer), @herbdool (tagged the 1.0.0 release) & @jenlampton (input/advice on how to proceed with a new release).

**Comment by klonos** [comment]
...feel free to unassign yourselves if you think there's nothing you can do.

**Comment by herbdool** [comment]
Thanks @klonos. First step I can make a new release and mention it's a security fix. Second, @jenlampton or @serundeputy can mark the old release as having a security issue (can't do it from github yet). Third, we'll probably need to find a new maintainer. @jromine I believe you've stepped away from Backdrop, am I correct?

**Comment by jromine** [comment]
I'm still following the project, but not active at present. Glad to see someone port this fix; I was about to look at doing that myself.

**Comment by jackaponte** [comment]
Wow, thanks for putting this on my radar y'all; hadn't noticed the new References D7 release. What a relief!

**Comment by Al-Rozhkov** [comment]
I think we can close this.

**Comment by klonos** [comment]
> @jenlampton or @serundeputy can mark the old release as having a security issue (can't do it from github yet).

Can't do that on b.org either; we do the opposite: mark the new release as a security release. I think it doesn't make sense otherwise either, since all releases prior to a security release should then be marked as having security issues. Anyways, point is: Done:

![image](https://cloud.githubusercontent.com/assets/2423362/25203305/1218d398-259c-11e7-90f5-55965eac10cc.png)
