### ISSUE TITLE
PDOException when using the select list widget on a user reference field

### ISSUE THREAD

**Issue by hosef** [backdrop-contrib/references#9]
In Backdrop, the `users_roles` table had a column named `rid` changed to `role`. This change causes a PDOExcception in the References module when searching for users with a particular role for the select list.

Changing the column name in the query appears to fix the issue for me.

`PDOException: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'r.rid' in 'where clause': SELECT u.* FROM {users} u INNER JOIN {users_roles} r ON u.uid = r.uid WHERE (r.rid IN (:db_condition_placeholder_0)) AND (u.uid <> :db_condition_placeholder_1) ORDER BY u.name ASC; Array ( [:db_condition_placeholder_0] => site_owner [:db_condition_placeholder_1] => 0 ) in _user_reference_potential_references_standard() (line 900 of /path/to/site/modules/contrib/references/user_reference/user_reference.module).`

**Comment by herbdool** [comment]
Added bug fix (in my capacity as member of Bug Fix Team).
